alter table deliverables add column "paper_submission_date" VARCHAR;
alter table deliverables add column "person_responsable" VARCHAR;
alter table deliverables add column "previous_report" VARCHAR;
alter table deliverables add column "date_edited" DATE;
alter table deliverables add column "completion_date" DATE;
alter table tasks add column "paper_submission_date" VARCHAR;
alter table tasks add column "person_responsable" VARCHAR;
alter table tasks add column "previous_report" VARCHAR;
alter table tasks add column "date_edited" DATE;
alter table tasks add column "completion_date" DATE;
alter table work_packages add column "previous_report" VARCHAR;
alter table work_packages add column "date_edited" DATE;
select * into tasks_20191201 from tasks;
select * into wps_20191201 from work_packages;
select * into deliverables_20191201 from deliverables;
