"""empty message

Revision ID: 416b14d7c752
Revises: 
Create Date: 2018-08-14 14:10:00.064462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416b14d7c752'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('work_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('deliverables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('work_package', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('responsible_partner', sa.String(), nullable=False),
    sa.Column('month_due', sa.Integer(), nullable=False),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_partner'], ['partners.name'], ),
    sa.ForeignKeyConstraint(['work_package'], ['work_packages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('responsible_partner', sa.String(), nullable=False),
    sa.Column('month_due', sa.Integer(), nullable=False),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['responsible_partner'], ['partners.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users2partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('partner', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['partner'], ['partners.name'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'partner', name='_username_partner_uc')
    )
    op.create_table('users2work_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('work_package', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.ForeignKeyConstraint(['work_package'], ['work_packages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'work_package', name='_username_work_package_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users2work_packages')
    op.drop_table('users2partners')
    op.drop_table('tasks')
    op.drop_table('deliverables')
    op.drop_table('work_packages')
    op.drop_table('users')
    op.drop_table('partners')
    # ### end Alembic commands ###
