"""empty message

Revision ID: b7f2c64064db
Revises: 416b14d7c752
Create Date: 2019-01-02 12:43:38.991823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f2c64064db'
down_revision = '416b14d7c752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_packages', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work_packages', 'status')
    # ### end Alembic commands ###
