"""empty message

Revision ID: bc915f504264
Revises: b7f2c64064db
Create Date: 2019-01-02 15:10:54.856558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc915f504264'
down_revision = 'b7f2c64064db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('work_package', sa.String(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'work_packages', ['work_package'], ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'work_package')
    # ### end Alembic commands ###
